name: ModuleTest
on: [push , workflow_dispatch]
jobs:
  Job1:
    needs: Job2
    runs-on: Ubuntu-latest
    steps:
      - name: step1
        run: echo "run completed"
  Job2:
    runs-on: Ubuntu-latest
    steps: 
      - name: npmci
        run: npm ci
        
    
  
  
